server:
  port: 8080

spring:
  h2:
    console:
      enabled: true

  datasource:
    url: jdbc:h2:file:./.db/testdb
    driver-class-name: org.h2.Driver
    username: sa
    password:

  # jpa설정
  jpa:
    hibernate:
      ddl-auto: update
    properties: # property 사용 설정
      hibernate: # hibernate property 설정
        format_sql: true